### ISSUE TITLE
build:sql:insert --force problem

### ISSUE THREAD

**Issue by Yoann53** [propelorm/PropelBundle#282] opened 2014-07-16 01:30 UTC
Hi,

i was following the guide linked at:
http://www.propelorm.org/cookbook/symfony2/symfony2-and-propel-in-real-life.html

when i arrive in the insert-sql step, there seems to be a problem:

the tables are NOT written in the database. 
my database is called "propeltest", and reading the sources, i found that it 
NEVER reach the part of the sql file reading, because of a control a 
step before:

in the PropelsqlManager , at the InsertSql method: 
inside that, there is a foreach . 
in my situation it quits the foreach before reading the sql file, 
because the condition.

    if (null !== $datasource && $database !== $datasource) { 
      // skip 
      break; 
    }

See this issue :  
https://github.com/propelorm/PropelBundle/issues/62

And results true: my database is 'propeltest' , and the datasource is 
'default' so it breaks the foreach and never reaches the sql query part.

The "break;" instruction is changed by the "continue" instruction. 
But now propel say me "All SQL statements have been inserted." but there is nothing created in my database.

The only way I found to correct that is to declare my connection in config.yml file and replace the name of the connection with the name of my database : 

    dbal:
        default_connection:         propeltest
        connections:
            propeltest:
                driver:             pdo_mysql
                user:               root
                password:           mysql
                dsn:                mysql:host=127.0.0.1;dbname=propeltest

Consequently, I have now two connections in the arg $connections in the setConnections($connections) function in /vendor/propel/propel1/generator/lib/util/PropelSqlManager.php line 51.

var_dump($connections) : 

    array(2) {
      ["propeltest"]=>
      array(8) {
        ["dsn"]=>
        string(38) "mysql:host=127.0.0.1;dbname=propeltest"
        ["user"]=>
        string(4) "root"
        ["password"]=>
        string(5) "mysql"
        ["classname"]=>
        string(8) "DebugPDO"
        ["options"]=>
        array(0) {
        }
        ["attributes"]=>
        array(0) {
        }
        ["settings"]=>
        array(0) {
        }
        ["model_paths"]=>
        array(2) {
          [0]=>
          string(4) "src/"
          [1]=>
          string(7) "vendor/"
        }
      }
      ["default"]=>
      array(8) {
        ["dsn"]=>
        string(38) "mysql:host=127.0.0.1;dbname=propeltest"
        ["user"]=>
        string(4) "root"
        ["password"]=>
        string(5) "mysql"
        ["classname"]=>
        string(8) "DebugPDO"
        ["options"]=>
        array(0) {
        }
        ["attributes"]=>
        array(0) {
        }
        ["settings"]=>
        array(0) {
        }
        ["model_paths"]=>
        array(2) {
           [0]=>
          string(4) "src/"
          [1]=>
          string(7) "vendor/"
        }
      }
    }

So propel try to insert two times my propeltest.sql file but the first time with propeltest connection and that works, the second time with default connection but that fails without error display.

I don't understand why the default connection is automatically created ?

**Comment by Gamesh** [comment] 2015-12-17 06:49
in the latest version it was changed from break to continue, although that does not solve problem. It just never executes the sql. Either there is something badly documented on how to use this command or this feature to create a DB from sql on a different connection is completely broken.

**Comment by havvg** [comment] 2016-01-23 22:36
I was just investigating the issue and probably found the cause.

The default connection, which name you set, is added to the list of connections as `default` - as you recognised when debugging. This is required, as the `default` database may be referenced by other bundles.

I tried your use-case multiple times, and it works fine for me. It generates two separate `sql` files, which will be inserted into the same database, but none of them is inserted twice.

Could you review your issue and maybe provide a PR on https://github.com/havvg/symfony-propel-edition with the schemas etc. causing the error?

**Comment by havvg** [comment] 2016-01-24 10:50
This should be fixed by #392, too. If you run into this issue again, please let me know.

**Closed by havvg** 2016-01-24 10:50 UTC
Labels: Bug
