### ISSUE TITLE
Form generator doesn't work if foreign key in a different schema

### ISSUE THREAD

**Issue by liamsorsby** [propelorm/PropelBundle#341] opened 2015-06-26 11:13 UTC
Initiating "propel:form:generate" "@appMyBundle" "Component" on the following schema:

app\MyBundle\Resources\config\schema.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<database name="default" namespace="app\MyBundle\Model" defaultIdMethod="native">

    <table name="book">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true" />
        <column name="title" type="varchar" primaryString="1" size="100" />
        <column name="ISBN" type="varchar" size="20" />
        <column name="author_id" type="integer" />
        <foreign-key foreignTable="author">
            <reference local="author_id" foreign="id" />
        </foreign-key>
    </table>

</database>
```

and the author table in a different schema:

app\AnotherBundle\Resources\config\schema.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<database name="default" namespace="app\AnotherBundle\Model" defaultIdMethod="native">

    <table name="author">
        <column name="id" type="integer" required="true" primaryKey="true" autoIncrement="true" />
        <column name="first_name" type="varchar" size="100" />
        <column name="last_name" type="varchar" size="100" />
    </table>

</database>
```

These two will build fine using propel:build, however when you use
```
propel:form:generate "@appMyBundle" "book"
```

It shows the following error: 
```
[ BuildException ]
Table "book" contains a foreign key to nonexistent table "author"
```

This is on "propel/propel-bundle": "1.4.5"

**Comment by havvg** [comment] 2016-01-23 21:55
Duplicate of #173.

**Closed by havvg** 2016-01-23 21:55 UTC
Labels: Bug, Forms
